etl:
  outputs:
    dev:
      dataset: dbt_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: config/datasync-pro-etl.json
      location: EU
      method: service-account
      priority: interactive
      project: datasync-pro
      threads: 1
      type: bigquery
  target: dev
