etl:
  target: prod # change to prod when deploy
  outputs:
    dev:
      dataset: raw_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: credentials/datasync-pro-etl.json
      location: EU
      method: service-account
      priority: interactive
      project: datasync-pro
      threads: 1
      type: bigquery
    prod:
      dataset: production_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: credentials/datasync-pro-etl.json
      location: EU
      method: service-account
      priority: interactive
      project: datasync-pro
      threads: 1
      type: bigquery


  
