version: 2

sources:
  - name: production_dataset # change production_dataset for development
    tables:
      - name: kassal_product_data
      - name: vda_product_data
      - name: kassal_store_data


