version: 2

models:
  - name: fact_product
    description: "Fact table for products, combining data from kassal and vda sources."
    columns:
      - name: product_id
        description: "Unique identifier for the product."
        tests:
          - not_null
          - unique
      - name: ean
        description: "Global Trade Item Number (EAN)."
        tests:
          - not_null
      - name: name
        description: "Product name."
      - name: weight
        description: "Weight of the product."
      - name: weight_unit
        description: "Unit of the weight."
      - name: kassal_image_url
        description: "URL of the product image from kassal."
      - name: vda_image_url
        description: "URL of the product image from vda."
      - name: created_at
        description: "Timestamp when the product was created."
      - name: updated_at
        description: "Timestamp when the product was last updated."
      - name: ingredients
        description: "Ingredients of the product."
      - name: vendor_id
        description: "Foreign key to the vendor table."
        tests:
          - relationships:
              to: ref('dim_vendor')
              field: vendor_id
      - name: category_id
        description: "Foreign key to the category table."
        tests:
          - relationships:
              to: ref('dim_category')
              field: category_id
      - name: nutrition
        description: "Nutritional information of the product."
      - name: brand
        description: "Brand of the product."
      - name: min_temp
        description: "Minimum temperature in Celsius for storage."
      - name: max_temp
        description: "Maximum temperature in Celsius for storage."
      - name: production_country
        description: "Country of production."

  - name: dim_store
    description: "Dimension table for store information."
    columns:
      - name: store_id
        description: "Unique identifier for the store."
        tests:
          - not_null
          - unique
      - name: group
        description: "Group the store belongs to."
      - name: name
        description: "Store name."
      - name: openingHours
        description: "Opening hours of the store."
      - name: url
        description: "Detail URL of the store."
      - name: fax
        description: "Fax number of the store."
      - name: email
        description: "Email address of the store."
      - name: phone
        description: "Phone number of the store."
      - name: logo_url
        description: "URL of the store's logo."
      - name: address
        description: "Physical address of the store."
      - name: position
        description: "Geographical position of the store."
      - name: website
        description: "Website of the store."

  - name: dim_category
    description: "Dimension table for product categories."
    columns:
      - name: category_id
        description: "Unique identifier for the category."
        tests:
          - not_null
          - unique
      - name: name
        description: "Name of the category."
      - name: parent_category_id
        description: "Identifier for the parent category. Currently set to NULL."

  - name: dim_vendor
    description: "Dimension table for vendors."
    columns:
      - name: vendor_id
        description: "Unique identifier for the vendor."
        tests:
          - not_null
          - unique
      - name: name
        description: "Vendor name."
      - name: gln
        description: "Global Location Number of the vendor."
      - name: country
        description: "Country of the vendor."

  - name: dim_price
    description: "Fact table for historical pricing information."
    columns:
      - name: price_id
        description: "Unique identifier for the price record."
        tests:
          - not_null
          - unique
      - name: product_id
        description: "Foreign key to the product table."
        tests:
          - relationships:
              to: ref('fact_product')
              field: product_id
      - name: store_id
        description: "Foreign key to the store table."
        tests:
          - relationships:
              to: ref('dim_store')
              field: store_id
      - name: price
        description: "Price of the product."
      - name: unit_price
        description: "Unit price of the product."
      - name: date
        description: "Date of the price record."
