-- WITH cleaned_data AS (
--     SELECT * FROM {{ ref('intermediate_model') }}
-- ),

-- price_data AS (
--     SELECT * FROM {{ ref('price_dim') }}
-- ),

-- product_fact AS (
--     SELECT
--         p.product_id,
--         p.name,
--         p.description,
--         p.gtin,
--         p.weight,
--         p.weight_unit,
--         p.image_url,
--         p.category_id,
--         p.vendor_id,
--         p.created_at,
--         p.updated_at,
--         p.labels,
--         p.allergens,
--         p.ingredients,
--         pr.price,
--         pr.unit_price,
--         pr.price_date,
--         s.store_id,
--         s.name AS store_name,
--         s.code AS store_code,
--         s.url AS store_url,
--         s.logo_url AS store_logo_url
--     FROM cleaned_data p
--     LEFT JOIN price_data pr
--     ON p.product_id = pr.product_id
--     LEFT JOIN `your_project.your_dataset.kassal_store_data` s
--     ON pr.store_id = s.store_id
-- )

-- SELECT * FROM product_fact
