# version: 2

# models:
#   - name: store_dim
#     description: "Store dimension table"
#     columns:
#       - name: store_id
#         description: "Store ID"
#       - name: name
#         description: "Store name"
#       - name: code
#         description: "Store code"
#       - name: url
#         description: "Store URL"
#       - name: logo_url
#         description: "Store logo URL"

#   - name: category_dim
#     description: "Category dimension table"
#     columns:
#       - name: category_id
#         description: "Category ID"
#       - name: name
#         description: "Category name"
#       - name: parent_category_id
#         description: "Parent category ID"

#   - name: vendor_dim
#     description: "Vendor dimension table"
#     columns:
#       - name: vendor_id
#         description: "Vendor ID"
#       - name: name
#         description: "Vendor name"
#       - name: gln
#         description: "Global Location Number"
#       - name: country
#         description: "Country"

#   - name: price_dim
#     description: "Price dimension table"
#     columns:
#       - name: price_id
#         description: "Price ID"
#       - name: product_id
#         description: "Product ID"
#       - name: store_id
#         description: "Store ID"
#       - name: price
#         description: "Price"
#       - name: unit_price
#         description: "Unit price"
#       - name: price_date
#         description: "Price date"

#   - name: product_fact
#     description: "Product fact table"
#     columns:
#       - name: product_id
#         description: "Product ID"
#       - name: name
#         description: "Product name"
#       - name: description
#         description: "Product description"
#       - name: gtin
#         description: "Global Trade Item Number"
#       - name: weight
#         description: "Product weight"
#       - name: weight_unit
#         description: "Weight unit"
#       - name: image_url
#         description: "Image URL"
#       - name: category_id
#         description: "Category ID"
#       - name: vendor_id
#         description: "Vendor ID"
#       - name: created_at
#         description: "Created timestamp"
#       - name: updated_at
#         description: "Updated timestamp"
#       - name: labels
#         description: "Product labels"
#       - name: allergens
#         description: "Product allergens"
#       - name: ingredients
#         description: "Product ingredients"
#       - name: price
#         description: "Product price"
#       - name: unit_price
#         description: "Unit price"
#       - name: price_date
#         description: "Price date"
#       - name: store_id
#         description: "Store ID"
#       - name: store_name
#         description: "Store name"
#       - name: store_code
#         description: "Store code"
#       - name: store_url
#         description: "Store URL"
#       - name: store_logo_url
#         description: "Store logo URL"
